name: Deploy Worker to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: SSH to VM and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          port: 22
          script: |
            set -e

            echo ">>> Go to project folder"
            cd ${{ secrets.VM_FOLDER }}

            echo ">>> Fix git safe directory"
            git config --global --add safe.directory ${{ secrets.VM_FOLDER }}

            echo ">>> Current commit on VM:"
            git rev-parse HEAD

            echo ">>> Pulling latest code..."
            git pull origin main

            echo ">>> New commit on VM:"
            git rev-parse HEAD

            echo ">>> Building images (no cache)..."
            docker compose build --no-cache

            echo ">>> Restarting containers..."
            docker compose down
            docker compose up --scale worker=1 -d

            echo ">>> Deployment done successfully."
