name: Deploy Worker to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH to VM and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            cd ${{ secrets.VM_FOLDER }}
            echo ">>> Pulling latest code..."
            git pull

            echo ">>> Building images..."
            docker compose build

            echo ">>> Stopping containers..."
            docker compose down

            echo ">>> Starting containers with worker=5 ..."
            docker compose up --scale worker=5 -d

            echo ">>> Deployment done successfully."
